default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: "username"
  password: "**********"

development:
  <<: *default
  database: app-usdProject_development



test:
  <<: *default
  database: app-usdProject_test

production:
  <<: *default
  database: app-usdProject_production
